config/routes.rb
MovieApp::Application.routes.draw do
  
  devise_for :users
  
  get 'landingpage' => 'landingpage#redirect'

  namespace :api do
    get 'promotion' => 'api#promotion'
    get 'movieinfo_promotion' => 'api#movieinfo_promotion'
    
    namespace :v2 do
      resources :movies, :only => [:index, :show] do
        member do
          get 'timetable'
        end
      end
      resources :records, :only => [:show]  
    end
    namespace :v1 do
      resources :campaigns, :only => [:index, :show] do
        collection do
          get 'announce_list'
        end
        member do
          get 'announce'
        end
      end  
      resources :users,:only => [:create, :update, :destroy] do
        collection do
          get 'friends_list'
          get 'user_info'
          #put : update
          #post : create

        end
      end
      resources :records,:only => [:create, :update, :destroy, :index, :show] do
        collection do
          get 'friend_stream'
          get 'get_movie_records'
          get 'get_movie_records_limit'
          get 'records_with_page'
        end
        member do
          post 'love'
          delete 'unlove'
        end
      end
      resources :theaters, :only => [:show, :index] do
        member do
          get 'get_movies_id'
          get 'get_movies_id_and_hall_str'
        end
      end
      resources :areas, :only => [:index]
      resources :movies do
        collection do
          get 'hot'
          get 'first_round'
          get 'second_round'
          get 'all'
          get 'comming'
          get 'this_week'
          get 'first_second_comming_hot'
          get 'first_second_comming_hot_update'
          get 'movies_info'
        end 
        member do
          get 'timetable'
          get 'update_release_date_running_time_youtube'
          get 'movie_info'
          get 'timetablev2'
        end
      end
      resources :channels, :only => [:index] do
        member do
          get 'channel_time'
        end
      end
      resources :comments,:only => [:create, :destroy]
      resources :streams,:only => [:index] do
        collection do
          get 'streams_with_page'
        end
      end
      resources :news, :only => [:index]

      resources :appprojects, :only => [:index]
    end
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  # attr_accessible :title, :body
  scope :by_id_desc, order('id DESC')
  belongs_to :user
end

app/controllers/api/v1/news_controller.rb
class Api::V1::NewsController < ApplicationController
  def index

    if params[:page]
      @news = News.by_id_desc.paginate(:page => params[:page], :per_page => 20)
    else
      @news = News.by_id_desc
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  def index
    @bloggers = User.blogger
    @news = News.all
  end

  def show
    @news = News.find(params[:id])
    @user = @news.user

    @news = News.first
    @user = User.first
  end

end

app/helpers/api/v1/news_helper.rb
module Api::V1::NewsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.haml
- @bloggers.each do |blogger|
  = link_to (image_tag "http://graph.facebook.com/#{blogger.fb_id}/picture?type=large"), user_path(blogger)

.news-content
- @news.each do |each_news|
  = link_to news_path(each_news) do
    .news-block
      = image_tag each_news.thumbnail_url
      = each_news.title

app/views/news/show.html.haml
.span3
  .well
    作者：
    .user-image
      = link_to (image_tag "http://graph.facebook.com/#{@user.fb_id}/picture?type=large"), user_path(@user)
    電影打卡
    = @user.records.size
    跟隨中
    = @user.friends.size
    跟隨者
    = @user.friends.size
    %hr
    近期文章
    - News.limit(2).each do |each_news|
      = link_to news_path(each_news) do
        .news-block
          = image_tag each_news.thumbnail_url
          %br
          = each_news.title
    %hr
    熱門文章
    - News.limit(2).each do |each_news|
      = link_to news_path(each_news) do
        .news-block
          = image_tag each_news.thumbnail_url
          %br
          = each_news.title

.span9
  .well
    文章主題
    = @news.text.html_safe
    %hr
    %hr
    %hr
    %hr
    %hr
    %hr
    %hr
    %hr
    %hr
    %hr
    %hr
    %hr