config/routes.rb
MovieApp::Application.routes.draw do
  
  devise_for :users
  
  get 'landingpage' => 'landingpage#redirect'

  namespace :api do
    get 'promotion' => 'api#promotion'
    get 'movieinfo_promotion' => 'api#movieinfo_promotion'
    
    namespace :v2 do
      resources :movies, :only => [:index, :show] do
        member do
          get 'timetable'
        end
      end
      resources :records, :only => [:show]  
    end
    namespace :v1 do
      resources :campaigns, :only => [:index, :show] do
        collection do
          get 'announce_list'
        end
        member do
          get 'announce'
        end
      end  
      resources :users,:only => [:create, :update, :destroy] do
        collection do
          get 'friends_list'
          get 'user_info'
          #put : update
          #post : create

        end
      end
      resources :records,:only => [:create, :update, :destroy, :index, :show] do
        collection do
          get 'friend_stream'
          get 'get_movie_records'
          get 'get_movie_records_limit'
          get 'records_with_page'
        end
        member do
          post 'love'
          delete 'unlove'
        end
      end
      resources :theaters, :only => [:show, :index] do
        member do
          get 'get_movies_id'
          get 'get_movies_id_and_hall_str'
        end
      end
      resources :areas, :only => [:index]
      resources :movies do
        collection do
          get 'hot'
          get 'first_round'
          get 'second_round'
          get 'all'
          get 'comming'
          get 'this_week'
          get 'first_second_comming_hot'
          get 'first_second_comming_hot_update'
          get 'movies_info'
        end 
        member do
          get 'timetable'
          get 'update_release_date_running_time_youtube'
          get 'movie_info'
          get 'timetablev2'
        end
      end
      resources :channels, :only => [:index] do
        member do
          get 'channel_time'
        end
      end
      resources :comments,:only => [:create, :destroy]
      resources :streams,:only => [:index] do
        collection do
          get 'streams_with_page'
        end
      end
      resources :news, :only => [:index]

      resources :appprojects, :only => [:index]
    end
  end

end

app/views/_partials/_footer.html.haml
%footer
  %p © Company 2012

app/views/_partials/_movie_user_review.html.haml
- records.each do |r|
  .review
    = link_to image_tag(user_avatar(r.user.fb_id)), user_path(r.user)
    = r.comment
    like count
    = r.love_count
    comments_count
    = r.comments_count
    create
    = r.created_at

app/views/_partials/_movies_container.html.haml
- movies.each do |m|
  .movie-block.span3
    = link_to movie_path(m),:title => "test" do
      =image_tag m.poster_url
      %h3= m.name
    .movie-info
      %span.view-count
        %i.icon-eye-open
        0
      %span.like-count
        %i.icon-thumbs-up
        0

app/views/_partials/_records_container.html.haml
- records.each do |r|
  .movie-block.span3
    = link_to record_path(r),:title => "test" do
      =image_tag r.movie.poster_url
      %h3= r.movie.name
    .movie-info
      %span.view-count
        %i.icon-eye-open>
        0
      %span.like-count
        %i.icon-thumbs-up>
        0

app/views/_partials/_topbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Monster",root_path, :class => "brand"    
      .nav-collapse
        %ul.nav
          %li
            = link_to "user_name", user_path(22)
          %li
            = link_to "電影資訊", movies_path
          %li
            = link_to "電影報", news_index_path
          %li
            = link_to "社群動態", people_path
        .navbar-search
          = form_tag "#", :method => :post do
            = text_field_tag "search","",:class => "search-query span3", :placeholder => "Search"
            .icon-search
        .pull-right
          = link_to "Facebook登入", user_omniauth_authorize_path(:facebook) , :class => "facebook-login"